//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsTestBunifu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cau5_view
    {
        public string MaNL { get; set; }
        public string TenNL { get; set; }
        public string DonVi { get; set; }
        public Nullable<double> SoLuongTieuThu { get; set; }
    }
}
