//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsTestBunifu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHDB
    {
        public string MaHDB { get; set; }
        public string MaDU { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public string KhuyenMai { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual DoUong DoUong { get; set; }
    }
}
