//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsTestBunifu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhanVien
    {
        public string MaNV { get; set; }
        public string ChucVu { get; set; }
        public decimal Luong { get; set; }
        public int SoNgayLamViec { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
