//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsTestBunifu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLCafeEntities1 : DbContext
    {
        public QLCafeEntities1()
            : base("name=QLCafeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ban> Bans { get; set; }
        public virtual DbSet<CaLam> CaLams { get; set; }
        public virtual DbSet<ChiTietCaLam> ChiTietCaLams { get; set; }
        public virtual DbSet<ChiTietHDB> ChiTietHDBs { get; set; }
        public virtual DbSet<ChiTietHDN> ChiTietHDNs { get; set; }
        public virtual DbSet<ChiTietLuong> ChiTietLuongs { get; set; }
        public virtual DbSet<CongThucDoUong> CongThucDoUongs { get; set; }
        public virtual DbSet<DoUong> DoUongs { get; set; }
        public virtual DbSet<HoaDonBan> HoaDonBans { get; set; }
        public virtual DbSet<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieux { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<Cau6_view> Cau6_view { get; set; }
        public virtual DbSet<Cau2_view> Cau2_view { get; set; }
    
        public virtual int Cau1_proc(string maDoUong, Nullable<int> nam, ObjectParameter sL)
        {
            var maDoUongParameter = maDoUong != null ?
                new ObjectParameter("MaDoUong", maDoUong) :
                new ObjectParameter("MaDoUong", typeof(string));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cau1_proc", maDoUongParameter, namParameter, sL);
        }
    
       
    
        
    
        [DbFunction("QLCafeEntities1", "cau9_func")]
        public virtual IQueryable<cau9_func_Result> cau9_func(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<cau9_func_Result>("[QLCafeEntities1].[cau9_func](@nam)", namParameter);
        }
    
        [DbFunction("QLCafeEntities1", "cau7_func")]
        public virtual IQueryable<Nullable<decimal>> cau7_func(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<decimal>>("[QLCafeEntities1].[cau7_func1](@nam)", namParameter);
        }
    
        [DbFunction("QLCafeEntities1", "cau8_func")]
        public virtual IQueryable<Nullable<double>> cau8_func(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<double>>("[QLCafeEntities1].[cau8_func1](@nam)", namParameter);
        }
    }
}
